import type { WorkflowDefinition, WorkflowKey } from "./contracts";

const definitions: Record<WorkflowKey, WorkflowDefinition> = {
  urgent_notice_response: {
    key: "urgent_notice_response",
    version: "wayne-notice-v1",
    displayName: "Urgent notice response",
    initialState: "identified",
    transitions: {
      identified: ["entitled", "staff_exception"],
      entitled: ["notice_validated", "staff_exception"],
      notice_validated: ["action_ready", "staff_exception"],
      action_ready: ["handed_off", "submitted", "staff_exception"],
      handed_off: ["confirming", "staff_exception"],
      submitted: ["confirming", "staff_exception"],
      confirming: ["resolved", "staff_exception"],
      staff_exception: ["notice_validated", "action_ready", "closed_unresolved"],
      resolved: [],
      closed_unresolved: [],
    },
    nextActions: {
      identified: "Verify access to the correct Wayne County case.",
      entitled: "Validate the notice against the current County source.",
      notice_validated: "Review the approved response steps and deadline.",
      action_ready: "Complete the official response or secure handoff.",
      handed_off: "Wait for an authoritative returned status.",
      submitted: "Wait for Wayne County to confirm receipt and outcome.",
      confirming: "Civya is reconciling the authoritative status.",
      staff_exception: "A staff owner must resolve the notice exception.",
      resolved: "The Wayne-approved response outcome is verified.",
      closed_unresolved: "The exception closed without a verified outcome.",
    },
    authoritativeStates: ["resolved"],
    terminalStates: ["resolved", "closed_unresolved"],
    completionAuthority: "Wayne-approved response/status definition",
  },
  payment_plan_navigation: {
    key: "payment_plan_navigation",
    version: "wayne-payment-plan-v1",
    displayName: "Payment-plan navigation",
    initialState: "identified",
    transitions: {
      identified: ["entitled", "staff_exception"],
      entitled: ["step_up", "handoff_created", "staff_exception"],
      step_up: ["handoff_created", "staff_exception"],
      handoff_created: ["provider_open", "cancelled", "expired"],
      provider_open: ["submitted", "cancelled", "expired"],
      submitted: ["confirming", "cancelled", "staff_exception"],
      confirming: ["active", "declined", "reversed", "mismatch", "staff_exception"],
      mismatch: ["confirming", "staff_exception"],
      staff_exception: ["entitled", "confirming", "closed_unresolved"],
      active: ["reversed"],
      declined: [],
      cancelled: [],
      expired: [],
      reversed: [],
      closed_unresolved: [],
    },
    nextActions: {
      identified: "Verify access to the correct property-tax case.",
      entitled: "Review the approved payment-plan options.",
      step_up: "Complete the required identity step-up.",
      handoff_created: "Continue to the official Wayne County or Chase site.",
      provider_open: "Complete or leave the official hosted session.",
      submitted: "Wayne County or Chase must confirm the result.",
      confirming: "Civya is reconciling the plan status.",
      active: "The authoritative active-plan status is verified.",
      declined: "Review other approved options or request staff help.",
      cancelled: "Restart the official handoff or request help.",
      expired: "Create a new authorized handoff session.",
      reversed: "A staff owner must review the reversed plan status.",
      mismatch: "A reconciliation owner must resolve the status mismatch.",
      staff_exception: "A staff owner must resolve the payment-plan exception.",
      closed_unresolved: "The exception closed without a verified plan status.",
    },
    authoritativeStates: ["active", "declined", "reversed"],
    terminalStates: ["declined", "cancelled", "expired", "reversed", "closed_unresolved"],
    completionAuthority: "Wayne plan status for the correct parcel and tax year",
  },
  document_readiness: {
    key: "document_readiness",
    version: "wayne-document-readiness-v1",
    displayName: "Document readiness",
    initialState: "requested",
    transitions: {
      requested: ["uploaded", "expired", "staff_exception"],
      uploaded: ["quarantined"],
      quarantined: ["scanning", "scan_failed"],
      scanning: ["clean", "rejected", "scan_failed"],
      clean: ["staff_review"],
      staff_review: ["ready", "needs_action", "rejected", "staff_exception"],
      needs_action: ["uploaded", "expired", "staff_exception"],
      scan_failed: ["scanning", "staff_exception"],
      staff_exception: ["scanning", "staff_review", "needs_action", "closed_unresolved"],
      ready: [],
      rejected: [],
      expired: [],
      closed_unresolved: [],
    },
    nextActions: {
      requested: "Upload the requested document through the private intake.",
      uploaded: "The file must enter quarantine.",
      quarantined: "Wait for isolated malware scanning.",
      scanning: "The scanner is checking the quarantined file.",
      clean: "A staff reviewer must confirm readiness.",
      staff_review: "Wait for the assigned document review.",
      needs_action: "Replace or correct the document without losing the case.",
      scan_failed: "The file stays quarantined while scanning is retried.",
      staff_exception: "A staff owner must resolve the document exception.",
      ready: "The document-readiness result is verified.",
      rejected: "The document cannot be used; follow the approved replacement path.",
      expired: "Upload a current document if the task still applies.",
      closed_unresolved: "The exception closed without a ready document.",
    },
    authoritativeStates: ["ready"],
    terminalStates: ["ready", "rejected", "expired", "closed_unresolved"],
    completionAuthority: "Passing scanner result and approved staff/readiness definition",
  },
  reminders_follow_through: {
    key: "reminders_follow_through",
    version: "wayne-reminders-v1",
    displayName: "Reminders and follow-through",
    initialState: "draft",
    transitions: {
      draft: ["consent_checked", "cancelled", "suppressed"],
      consent_checked: ["scheduled", "suppressed", "cancelled"],
      scheduled: ["queued", "cancelled", "suppressed"],
      queued: ["sent", "failed", "suppressed", "cancelled"],
      sent: ["delivered", "failed", "suppressed"],
      failed: ["queued", "cancelled", "suppressed", "staff_exception"],
      staff_exception: ["queued", "cancelled", "closed_unresolved"],
      delivered: [],
      suppressed: [],
      cancelled: [],
      closed_unresolved: [],
    },
    nextActions: {
      draft: "Confirm consent and suppression before scheduling.",
      consent_checked: "Schedule the approved reminder.",
      scheduled: "Queue the message at the approved time.",
      queued: "Wait for the provider delivery attempt.",
      sent: "Wait for a delivery receipt.",
      delivered: "The reminder was delivered; the underlying task remains separate.",
      failed: "Retry within policy or request staff follow-through.",
      suppressed: "Do not send unless suppression is authoritatively cleared.",
      cancelled: "No reminder will be sent.",
      staff_exception: "A staff owner must resolve the reminder exception.",
      closed_unresolved: "The reminder closed without delivery.",
    },
    authoritativeStates: ["delivered"],
    terminalStates: ["delivered", "suppressed", "cancelled", "closed_unresolved"],
    completionAuthority: "Provider receipt for delivery only; separate task evidence for outcome",
  },
  human_partner_handoff: {
    key: "human_partner_handoff",
    version: "wayne-human-partner-v1",
    displayName: "Human or authorized-partner handoff",
    initialState: "requested",
    transitions: {
      requested: ["authorized", "declined", "expired"],
      authorized: ["assigned", "revoked", "expired"],
      assigned: ["shared", "declined", "revoked", "expired", "staff_exception"],
      shared: ["acknowledged", "declined", "revoked", "expired", "staff_exception"],
      acknowledged: ["resolved", "declined", "expired", "staff_exception"],
      staff_exception: ["assigned", "acknowledged", "closed_unresolved"],
      resolved: [],
      declined: [],
      expired: [],
      revoked: [],
      closed_unresolved: [],
    },
    nextActions: {
      requested: "Confirm the authorized purpose and minimum necessary fields.",
      authorized: "Assign an approved staff or partner owner.",
      assigned: "Share only the authorized fields through the approved channel.",
      shared: "Wait for the assigned owner to acknowledge the request.",
      acknowledged: "Track the referral or assistance to closure.",
      resolved: "The assigned owner recorded approved closure evidence.",
      declined: "Return to Civya for another approved assistance path.",
      expired: "Reauthorize the handoff if it is still needed.",
      revoked: "Stop sharing and return to a staff-assisted path.",
      staff_exception: "A staff owner must resolve the handoff exception.",
      closed_unresolved: "The handoff closed without a verified resolution.",
    },
    authoritativeStates: ["resolved"],
    terminalStates: ["resolved", "declined", "expired", "revoked", "closed_unresolved"],
    completionAuthority: "Approved staff/partner closure evidence plus any required Wayne status",
  },
};

export function getWorkflowDefinition(key: WorkflowKey): WorkflowDefinition {
  return definitions[key];
}

export function listWorkflowDefinitions(): readonly WorkflowDefinition[] {
  return Object.values(definitions);
}
